[month]
january="Januar"
february="Februar"
march="März"
april="April"
may="Mai"
june="Juni"
july="Juli"
august="August"
september="September"
october="Oktober"
november="November"
december="Dezember"
[week_day]
monday="Mo"
tuesday="Di"
wednesday="Mi"
friday="Fr"
saturday="Sa"
sunday="So"
